import pygame

SCREEN_WIDTH = 650
SCREEN_HEIGHT = 650
GAME_SPEED_DELAY = 200

TITLE_FONT = "DoubleGravity/assets/fonts/LathiertrialRegular-ax449.otf"
TEXT_FONT = "DoubleGravity/assets/fonts/CreamySugar-gxnGR.ttf"

SCREEN_LEFT_EDGE_X = 10
SCREEN_RIGHT_EDGE_X = 640
SCREEN_UPPER_EDGE_Y = 10
SCREEN_LOWER_EDGE_Y = 640

RED_WIDTH = RED_HEIGHT = BLUE_WIDTH = BLUE_HEIGHT = 40
